### ISSUE TITLE
Move files one level up

### ISSUE THREAD

**Issue by rohitmanglik** [rohitmanglik/lead-forward-tool#1]
Currently all files are under EduGorilla folder. They should be in root level.

**Comment by rohitmanglik** [comment]
Even though the files are moved to root folder, EduGorilla folder still has files. Please remove them.

**Comment by rohitmanglik** [comment]
There are still two copied of same code. One is in root folder and other is inside edugorilla folder. Please remove the code insude edugorilla folder.

**Comment by tjtarunkumar** [comment]
Done
