### ISSUE TITLE
Show count of total number of emails sent

### ISSUE THREAD

**Issue by rohitmanglik** [rohitmanglik/lead-forward-tool#2]
If an email is sent to xyz coaching Institute, we should show count of how many emails were sent.

**Comment by tjtarunkumar** [comment]
I have fixed that issue.

**Comment by rohitmanglik** [comment]
Just checked. It shows count - perfect. 

However when I changed starting data to 8 and end date to today, count should have decreased to one. But it's two in this case as well.

**Comment by tjtarunkumar** [comment]
Issue fixed.
